# Generated by Django 5.2.3 on 2025-06-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkUnit',
            fields=[
                ('wu_intersection_node_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('delivery_status', models.CharField(max_length=50)),
                ('rfdb_production_status', models.CharField(blank=True, max_length=50, null=True)),
                ('rfdb_qc_status', models.CharField(blank=True, max_length=50, null=True)),
                ('siloc_status', models.CharField(blank=True, max_length=50, null=True)),
                ('rfdb_completion_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tm_production_inputs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Production_inputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_completion_date', models.DateField(unique=True)),
                ('atdb_output', models.IntegerField(default=0)),
                ('production_output', models.IntegerField(default=0)),
                ('siloc_output', models.IntegerField(default=0)),
                ('qc_output', models.IntegerField(default=0)),
                ('path_association_output', models.IntegerField(default=0)),
                ('delivery', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Daily Production Input',
                'verbose_name_plural': 'Daily Production Inputs',
                'db_table': 'tm_production_inputs',
                'ordering': ['production_completion_date'],
            },
        ),
    ]
